baseURL = 'https://freemandune.github.io/page/'
languageCode = 'es-ES'
title = 'Web de pruebas de HUGO'
theme = 'beautifulhugo'
sectionPagesMenu = 'main'
[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

